---
- name: Install opencode
  ansible.builtin.shell: pnpm install --global opencode-ai
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

- name: Create symbolic link for config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ xdg_config_home }}/opencode"
    state: link
