---
- name: Install opencode
  when: ansible_system == "Darwin"
  community.general.homebrew:
    name: "sst/tap/opencode"
    state: present

- name: Create symbolic link for config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ xdg_config_home }}/opencode"
    state: link
